/* Generated by Yosys 0.60+8 (git sha1 0e31e389f2cf5b29e900e56285b3d1f058f38c29, g++ 15.2.1 -O2 -flto=auto -ffat-lto-objects -fexceptions -fstack-protector-strong -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -O3) */

module \$paramod$b564b14d9fd308e618b07377286ecb02226d23aa\clock_divider (clk, rstb, div, dis, gclk, grstb);
  input clk;
  wire clk;
  input rstb;
  wire rstb;
  input [6:0] div;
  wire [6:0] div;
  input dis;
  wire dis;
  output gclk;
  wire gclk;
  output grstb;
  wire grstb;
  wire _gen__00_;
  wire [5:0] _gen__01_;
  wire [5:0] _gen__02_;
  wire [5:0] _gen__03_;
  wire [5:0] _gen__04_;
  wire _gen__05_;
  wire _gen__06_;
  wire _gen__07_;
  wire _gen__08_;
  wire _gen__09_;
  wire [31:0] _gen__10_;
  wire bypass;
  wire bypass_latched;
  wire clk_b;
  wire clk_f;
  wire clk_r;
  wire [5:0] counter;
  wire stop_div;
  wire [3:0] sync_rstb;
  \$add  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd6),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd6),
    .Y_WIDTH(32'd6)
  ) _gen__11_ (
    .A(_gen__03_),
    .B(_gen__04_),
    .Y(_gen__02_)
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd6),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd6),
    .Y_WIDTH(32'd6)
  ) _gen__12_ (
    .A({ _gen__05_, _gen__05_, _gen__05_, _gen__05_, _gen__05_, _gen__05_ }),
    .B(div[6:1]),
    .Y(_gen__03_)
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd6)
  ) _gen__13_ (
    .A(div[0]),
    .B(clk_r),
    .Y(_gen__04_)
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__14_ (
    .A(clk_r),
    .B(div[0]),
    .Y(_gen__00_)
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__15_ (
    .A(bypass_latched),
    .B(clk),
    .Y(clk_b)
  );
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd0),
    .WIDTH(32'd1)
  ) clk_r_reg /* _gen__16_ */ (
    .ARST(rstb),
    .CLK(clk),
    .D(_gen__06_),
    .EN(_gen__09_),
    .Q(clk_r)
  );
  \$dlatch  #(
    .EN_POLARITY(32'd0),
    .WIDTH(32'd1)
  ) bypass_latched_reg /* _gen__17_ */ (
    .D(bypass),
    .EN(clk),
    .Q(bypass_latched)
  );
  \$logic_not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__18_ (
    .A(_gen__08_),
    .Y(bypass)
  );
  \$not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__19_ (
    .A(stop_div),
    .Y(_gen__05_)
  );
  \$not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__20_ (
    .A(_gen__07_),
    .Y(_gen__06_)
  );
  \$or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__21_ (
    .A(bypass),
    .B(dis),
    .Y(stop_div)
  );
  \$or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__22_ (
    .A(clk_r),
    .B(stop_div),
    .Y(_gen__07_)
  );
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(4'h0),
    .CLK_POLARITY(1'h1),
    .WIDTH(32'd4)
  ) _gen__23_ (
    .ARST(rstb),
    .CLK(gclk),
    .D({ sync_rstb[2:0], 1'h1 }),
    .Q(sync_rstb)
  );
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(1'h0),
    .WIDTH(32'd1)
  ) clk_f_reg /* _gen__24_ */ (
    .ARST(rstb),
    .CLK(clk),
    .D(_gen__00_),
    .Q(clk_f)
  );
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(6'h00),
    .CLK_POLARITY(1'h1),
    .WIDTH(32'd6)
  ) _gen__25_ (
    .ARST(rstb),
    .CLK(clk),
    .D(_gen__01_),
    .Q(counter)
  );
  \$mux  #(
    .WIDTH(32'd6)
  ) _gen__26_ (
    .A(_gen__02_),
    .B(_gen__10_[5:0]),
    .S(_gen__09_),
    .Y(_gen__01_)
  );
  \$reduce_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd6),
    .Y_WIDTH(32'd1)
  ) _gen__27_ (
    .A(div[6:1]),
    .Y(_gen__08_)
  );
  \$reduce_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd5),
    .Y_WIDTH(32'd1)
  ) _gen__28_ (
    .A(counter[5:1]),
    .Y(_gen__09_)
  );
  \$sub  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd6),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd32),
    .Y_WIDTH(32'd32)
  ) _gen__29_ (
    .A(counter),
    .B(32'd1),
    .Y(_gen__10_)
  );
  CLOCK_MIXER g_mix (
    .A(clk_r),
    .B(clk_f),
    .C(clk_b),
    .O(gclk)
  );
  assign grstb = sync_rstb[3];
endmodule

module CLOCK_MIXER(A, B, C, O);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output O;
  wire O;
  wire _gen__0_;
  \$or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__1_ (
    .A(A),
    .B(B),
    .Y(_gen__0_)
  );
  \$or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__2_ (
    .A(_gen__0_),
    .B(C),
    .Y(O)
  );
endmodule

module ana_ctrl(prim_clk, prim_rstb, atpg, trig, ms_adc_eoc, ms_adc_soc, ms_adc_clk, ms_afe_sel, ms_afe_phase, ms_afe_phase_update, meas_state, meas_phase, meas_eoc_p, meas_eop);
  input prim_clk;
  wire prim_clk;
  input prim_rstb;
  wire prim_rstb;
  input atpg;
  wire atpg;
  input trig;
  wire trig;
  input ms_adc_eoc;
  wire ms_adc_eoc;
  output ms_adc_soc;
  wire ms_adc_soc;
  output ms_adc_clk;
  wire ms_adc_clk;
  output [3:0] ms_afe_sel;
  wire [3:0] ms_afe_sel;
  output [3:0] ms_afe_phase;
  wire [3:0] ms_afe_phase;
  output ms_afe_phase_update;
  wire ms_afe_phase_update;
  output [2:0] meas_state;
  wire [2:0] meas_state;
  output [3:0] meas_phase;
  wire [3:0] meas_phase;
  output meas_eoc_p;
  wire meas_eoc_p;
  output meas_eop;
  wire meas_eop;
  wire [3:0] _gen__00_;
  wire [3:0] _gen__01_;
  wire [2:0] _gen__02_;
  wire _gen__03_;
  wire _gen__04_;
  wire _gen__05_;
  wire _gen__06_;
  wire _gen__07_;
  wire _gen__08_;
  wire _gen__09_;
  wire _gen__10_;
  wire _gen__11_;
  wire _gen__12_;
  wire _gen__13_;
  wire _gen__14_;
  wire _gen__15_;
  wire _gen__16_;
  wire _gen__17_;
  wire _gen__18_;
  wire _gen__19_;
  wire _gen__20_;
  wire [31:0] _gen__21_;
  wire [2:0] _gen__22_;
  wire [2:0] _gen__23_;
  wire [2:0] _gen__24_;
  wire [2:0] _gen__25_;
  wire [2:0] _gen__26_;
  wire [2:0] _gen__27_;
  wire [3:0] _gen__28_;
  wire [3:0] afe_sel;
  wire [3:0] counter;
  wire phase_update;
  wire [1:0] sync_eoc;
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd4),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd4),
    .Y_WIDTH(32'd4)
  ) _gen__29_ (
    .A(afe_sel),
    .B({ _gen__14_, _gen__14_, _gen__14_, _gen__14_ }),
    .Y(ms_afe_sel)
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__30_ (
    .A(_gen__08_),
    .B(_gen__14_),
    .Y(ms_adc_soc)
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__31_ (
    .A(_gen__09_),
    .B(trig),
    .Y(_gen__04_)
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd4),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd4),
    .Y_WIDTH(32'd4)
  ) _gen__32_ (
    .A(meas_phase),
    .B({ _gen__14_, _gen__14_, _gen__14_, _gen__14_ }),
    .Y(ms_afe_phase)
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__33_ (
    .A(phase_update),
    .B(_gen__14_),
    .Y(ms_afe_phase_update)
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__34_ (
    .A(_gen__05_),
    .B(meas_phase[3]),
    .Y(meas_eop)
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__35_ (
    .A(sync_eoc[0]),
    .B(_gen__11_),
    .Y(_gen__05_)
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__36_ (
    .A(_gen__05_),
    .B(_gen__12_),
    .Y(meas_eoc_p)
  );
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(4'h0),
    .CLK_POLARITY(32'd1),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd4)
  ) _gen__37_ (
    .ARST(prim_rstb),
    .CLK(prim_clk),
    .D(_gen__01_),
    .EN(_gen__06_),
    .Q(meas_phase)
  );
  \$reduce_bool  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .Y_WIDTH(32'd1)
  ) _gen__38_ (
    .A({ _gen__13_, _gen__10_ }),
    .Y(_gen__06_)
  );
  \$logic_not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd4),
    .Y_WIDTH(32'd1)
  ) _gen__39_ (
    .A(counter),
    .Y(_gen__07_)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd4),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd4),
    .Y_WIDTH(32'd1)
  ) _gen__40_ (
    .A(counter),
    .B(4'h9),
    .Y(_gen__08_)
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__41_ (
    .A(_gen__09_),
    .B(trig),
    .Y(_gen__10_)
  );
  \$logic_not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__42_ (
    .A(sync_eoc[1]),
    .Y(_gen__11_)
  );
  \$logic_not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__43_ (
    .A(meas_phase[3]),
    .Y(_gen__12_)
  );
  \$logic_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__44_ (
    .A(meas_eoc_p),
    .B(meas_eop),
    .Y(_gen__13_)
  );
  \$not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__45_ (
    .A(atpg),
    .Y(_gen__14_)
  );
  \$or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__46_ (
    .A(_gen__04_),
    .B(meas_eoc_p),
    .Y(_gen__15_)
  );
  \$or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__47_ (
    .A(_gen__15_),
    .B(meas_eop),
    .Y(_gen__03_)
  );
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(4'h0),
    .CLK_POLARITY(1'h1),
    .WIDTH(32'd4)
  ) _gen__48_ (
    .ARST(prim_rstb),
    .CLK(prim_clk),
    .D(_gen__00_),
    .Q(counter)
  );
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(2'h3),
    .CLK_POLARITY(1'h1),
    .WIDTH(32'd2)
  ) _gen__49_ (
    .ARST(prim_rstb),
    .CLK(prim_clk),
    .D({ sync_eoc[0], ms_adc_eoc }),
    .Q(sync_eoc)
  );
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(1'h1),
    .WIDTH(32'd1)
  ) phase_update_reg /* _gen__50_ */ (
    .ARST(prim_rstb),
    .CLK(prim_clk),
    .D(_gen__03_),
    .Q(phase_update)
  );
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(3'h0),
    .CLK_POLARITY(1'h1),
    .WIDTH(32'd3)
  ) _gen__51_ (
    .ARST(prim_rstb),
    .CLK(prim_clk),
    .D(_gen__02_),
    .Q(meas_state)
  );
  \$pmux  #(
    .S_WIDTH(32'd5),
    .WIDTH(32'd4)
  ) _gen__52_ (
    .A(4'h0),
    .B(20'h12456),
    .S({ _gen__20_, _gen__19_, _gen__18_, _gen__17_, _gen__16_ }),
    .Y(afe_sel)
  );
  \$mux  #(
    .WIDTH(32'd4)
  ) _gen__53_ (
    .A(_gen__21_[3:0]),
    .B(4'hf),
    .S(_gen__07_),
    .Y(_gen__00_)
  );
  \$mux  #(
    .WIDTH(32'd4)
  ) _gen__54_ (
    .A(_gen__28_),
    .B(4'h1),
    .S(_gen__10_),
    .Y(_gen__01_)
  );
  \$pmux  #(
    .S_WIDTH(32'd6),
    .WIDTH(32'd3)
  ) _gen__55_ (
    .A(3'h0),
    .B({ _gen__22_, _gen__23_, _gen__24_, _gen__25_, _gen__26_, _gen__27_ }),
    .S({ _gen__09_, _gen__19_, _gen__18_, _gen__17_, _gen__16_, _gen__20_ }),
    .Y(_gen__02_)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _gen__56_ (
    .A(meas_state),
    .B(3'h4),
    .Y(_gen__20_)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _gen__57_ (
    .A(meas_state),
    .B(3'h6),
    .Y(_gen__16_)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _gen__58_ (
    .A(meas_state),
    .B(3'h7),
    .Y(_gen__17_)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _gen__59_ (
    .A(meas_state),
    .B(3'h3),
    .Y(_gen__18_)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _gen__60_ (
    .A(meas_state),
    .B(3'h1),
    .Y(_gen__19_)
  );
  \$logic_not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _gen__61_ (
    .A(meas_state),
    .Y(_gen__09_)
  );
  \$sub  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd4),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd32),
    .Y_WIDTH(32'd32)
  ) _gen__62_ (
    .A(counter),
    .B(32'd1),
    .Y(_gen__21_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _gen__63_ (
    .A(3'h0),
    .B(3'h1),
    .S(trig),
    .Y(_gen__22_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _gen__64_ (
    .A(3'h1),
    .B(3'h3),
    .S(meas_eop),
    .Y(_gen__23_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _gen__65_ (
    .A(3'h3),
    .B(3'h7),
    .S(meas_eop),
    .Y(_gen__24_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _gen__66_ (
    .A(3'h7),
    .B(3'h6),
    .S(meas_eop),
    .Y(_gen__25_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _gen__67_ (
    .A(3'h6),
    .B(3'h4),
    .S(meas_eop),
    .Y(_gen__26_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _gen__68_ (
    .A(3'h4),
    .B(3'h0),
    .S(meas_eop),
    .Y(_gen__27_)
  );
  \$mux  #(
    .WIDTH(32'd4)
  ) _gen__69_ (
    .A(4'hx),
    .B({ meas_phase[2:0], meas_phase[3] }),
    .S(_gen__13_),
    .Y(_gen__28_)
  );
  assign ms_adc_clk = prim_clk;
endmodule

module dsp(prim_clk, prim_rstb, enable, offset_tref, offset_oref, offset_gain, sensitivity_tref, sensitivity_oref, sensitivity_gain, ms_adc_data, meas_state, meas_phase, meas_eoc_p, meas_eop, meas_data, meas_data_p);
  input prim_clk;
  wire prim_clk;
  input prim_rstb;
  wire prim_rstb;
  input enable;
  wire enable;
  input [7:0] offset_tref;
  wire [7:0] offset_tref;
  input [7:0] offset_oref;
  wire [7:0] offset_oref;
  input [7:0] offset_gain;
  wire [7:0] offset_gain;
  input [7:0] sensitivity_tref;
  wire [7:0] sensitivity_tref;
  input [7:0] sensitivity_oref;
  wire [7:0] sensitivity_oref;
  input [7:0] sensitivity_gain;
  wire [7:0] sensitivity_gain;
  input [11:0] ms_adc_data;
  wire [11:0] ms_adc_data;
  input [2:0] meas_state;
  wire [2:0] meas_state;
  input [3:0] meas_phase;
  wire [3:0] meas_phase;
  input meas_eoc_p;
  wire meas_eoc_p;
  input meas_eop;
  wire meas_eop;
  output [11:0] meas_data;
  wire [11:0] meas_data;
  output meas_data_p;
  wire meas_data_p;
endmodule

module opcg(tck, trstb, tapp_active, tscan_exe, texe_done, gclk, gclk_rstb, gclk_app_active, clk);
  input tck;
  wire tck;
  input trstb;
  wire trstb;
  input tapp_active;
  wire tapp_active;
  input tscan_exe;
  wire tscan_exe;
  output texe_done;
  wire texe_done;
  input gclk;
  wire gclk;
  input gclk_rstb;
  wire gclk_rstb;
  output gclk_app_active;
  wire gclk_app_active;
  output clk;
  wire clk;
  wire _gen__00_;
  wire _gen__01_;
  wire _gen__02_;
  wire _gen__03_;
  wire _gen__04_;
  wire _gen__05_;
  wire _gen__06_;
  wire _gen__07_;
  wire _gen__08_;
  wire _gen__09_;
  wire _gen__10_;
  wire _gen__11_;
  wire [7:0] _gen__12_;
  wire _gen__13_;
  wire _gen__14_;
  wire _gen__15_;
  wire _gen__16_;
  wire [1:0] exe_done_resync;
  wire [1:0] in_app_resync;
  wire pulse_enable;
  wire [2:0] scan_exe_resync;
  wire [7:0] state;
  wire tck_enable;
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__17_ (
    .A(tck_enable),
    .B(tck),
    .Y(_gen__01_)
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__18_ (
    .A(pulse_enable),
    .B(gclk),
    .Y(_gen__02_)
  );
  \$reduce_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .Y_WIDTH(32'd1)
  ) _gen__19_ (
    .A({ state[2], state[0] }),
    .Y(_gen__03_)
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__20_ (
    .A(_gen__13_),
    .B(state[4]),
    .Y(_gen__04_)
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__21_ (
    .A(_gen__14_),
    .B(state[2]),
    .Y(_gen__05_)
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__22_ (
    .A(in_app_resync[1]),
    .B(_gen__03_),
    .Y(_gen__06_)
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__23_ (
    .A(_gen__15_),
    .B(state[4]),
    .Y(_gen__07_)
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__24_ (
    .A(_gen__16_),
    .B(state[5]),
    .Y(_gen__08_)
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__25_ (
    .A(_gen__14_),
    .B(state[0]),
    .Y(_gen__09_)
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__26_ (
    .A(scan_exe_resync[2]),
    .B(state[5]),
    .Y(_gen__10_)
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__27_ (
    .A(scan_exe_resync[2]),
    .B(state[4]),
    .Y(_gen__11_)
  );
  \$reduce_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .Y_WIDTH(32'd1)
  ) _gen__28_ (
    .A({ _gen__04_, _gen__05_ }),
    .Y(_gen__12_[0])
  );
  \$reduce_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _gen__29_ (
    .A({ _gen__07_, _gen__08_, _gen__09_ }),
    .Y(_gen__12_[4])
  );
  \$reduce_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .Y_WIDTH(32'd1)
  ) _gen__30_ (
    .A({ state[1], _gen__10_ }),
    .Y(_gen__12_[5])
  );
  \$reduce_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _gen__31_ (
    .A({ state[7], state[3:2] }),
    .Y(_gen__00_)
  );
  \$adff  #(
    .ARST_POLARITY(1'h0),
    .ARST_VALUE(8'h01),
    .CLK_POLARITY(1'h1),
    .WIDTH(32'd8)
  ) _gen__32_ (
    .ARST(gclk_rstb),
    .CLK(gclk),
    .D({ state[6], _gen__11_, _gen__12_[5:4], state[7], _gen__06_, state[3], _gen__12_[0] }),
    .Q(state)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd2),
    .Y_WIDTH(32'd1)
  ) _gen__33_ (
    .A({ in_app_resync[1], scan_exe_resync[2] }),
    .B(2'h2),
    .Y(_gen__13_)
  );
  \$logic_not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .Y_WIDTH(32'd1)
  ) _gen__34_ (
    .A({ in_app_resync[1], scan_exe_resync[2] }),
    .Y(_gen__15_)
  );
  \$not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__35_ (
    .A(scan_exe_resync[2]),
    .Y(_gen__16_)
  );
  \$not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__36_ (
    .A(in_app_resync[1]),
    .Y(_gen__14_)
  );
  \$dlatch  #(
    .EN_POLARITY(32'd0),
    .WIDTH(32'd1)
  ) tck_enable_reg /* _gen__37_ */ (
    .D(state[4]),
    .EN(tck),
    .Q(tck_enable)
  );
  \$dlatch  #(
    .EN_POLARITY(32'd0),
    .WIDTH(32'd1)
  ) pulse_enable_reg /* _gen__38_ */ (
    .D(_gen__00_),
    .EN(gclk),
    .Q(pulse_enable)
  );
  \$or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__39_ (
    .A(_gen__01_),
    .B(_gen__02_),
    .Y(clk)
  );
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(2'h0),
    .CLK_POLARITY(1'h1),
    .WIDTH(32'd2)
  ) _gen__40_ (
    .ARST(trstb),
    .CLK(tck),
    .D({ exe_done_resync[0], state[5] }),
    .Q(exe_done_resync)
  );
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(3'h0),
    .CLK_POLARITY(1'h1),
    .WIDTH(32'd3)
  ) _gen__41_ (
    .ARST(gclk_rstb),
    .CLK(gclk),
    .D({ scan_exe_resync[1:0], tscan_exe }),
    .Q(scan_exe_resync)
  );
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(2'h0),
    .CLK_POLARITY(1'h1),
    .WIDTH(32'd2)
  ) _gen__42_ (
    .ARST(gclk_rstb),
    .CLK(gclk),
    .D({ in_app_resync[0], tapp_active }),
    .Q(in_app_resync)
  );
  assign { _gen__12_[7:6], _gen__12_[3:1] } = { state[6], _gen__11_, state[7], _gen__06_, state[3] };
  assign gclk_app_active = in_app_resync[1];
  assign texe_done = exe_done_resync[1];
endmodule

module tap(prim_gclk, prim_rstb, trstb, tck, tdi, tdo, tde, texe_done, tscan_end, tscan_start, tscan_enable, tscan_exe, tapp_active);
  input prim_gclk;
  wire prim_gclk;
  input prim_rstb;
  wire prim_rstb;
  input trstb;
  wire trstb;
  input tck;
  wire tck;
  input tdi;
  wire tdi;
  output tdo;
  wire tdo;
  output tde;
  wire tde;
  input texe_done;
  wire texe_done;
  input tscan_end;
  wire tscan_end;
  output tscan_start;
  wire tscan_start;
  output tscan_enable;
  wire tscan_enable;
  output tscan_exe;
  wire tscan_exe;
  output tapp_active;
  wire tapp_active;
  wire [4:0] _gen__00_;
  wire _gen__01_;
  wire _gen__02_;
  wire [4:0] _gen__03_;
  wire _gen__04_;
  wire [31:0] _gen__05_;
  wire [4:0] _gen__06_;
  wire _gen__07_;
  wire _gen__08_;
  wire _gen__09_;
  wire _gen__10_;
  wire _gen__11_;
  wire _gen__12_;
  wire _gen__13_;
  wire _gen__14_;
  wire _gen__15_;
  wire _gen__16_;
  wire _gen__17_;
  wire _gen__18_;
  wire _gen__19_;
  wire _gen__20_;
  wire _gen__21_;
  wire _gen__22_;
  wire _gen__23_;
  wire _gen__24_;
  wire _gen__25_;
  wire _gen__26_;
  wire _gen__27_;
  wire [4:0] _gen__28_;
  wire _gen__29_;
  wire _gen__30_;
  wire _gen__31_;
  wire [31:0] _gen__32_;
  wire [2:0] _gen__33_;
  wire [2:0] _gen__34_;
  wire [2:0] _gen__35_;
  wire [2:0] _gen__36_;
  wire [2:0] _gen__37_;
  wire [2:0] _gen__38_;
  wire [7:0] cmd;
  wire cmd_filled;
  wire [4:0] counter;
  wire [2:0] next_state;
  wire scan_filled;
  wire [2:0] state;
  wire [4:0] window_counter;
  wire window_elapsed;
  \$add  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd5),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd32),
    .Y_WIDTH(32'd32)
  ) _gen__39_ (
    .A(window_counter),
    .B(_gen__32_),
    .Y({ _gen__05_[31:5], _gen__03_ })
  );
  \$add  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd5),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd5),
    .Y_WIDTH(32'd5)
  ) _gen__40_ (
    .A(counter),
    .B(5'h01),
    .Y(_gen__06_)
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__41_ (
    .A(tscan_enable),
    .B(tscan_end),
    .Y(tdo)
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__42_ (
    .A(tscan_enable),
    .B(tdi),
    .Y(tscan_start)
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__43_ (
    .A(_gen__15_),
    .B(_gen__27_),
    .Y(scan_filled)
  );
  \$adffe  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(8'h00),
    .CLK_POLARITY(32'd0),
    .EN_POLARITY(32'd1),
    .WIDTH(32'd8)
  ) _gen__44_ (
    .ARST(trstb),
    .CLK(tck),
    .D({ cmd[6:0], tdi }),
    .EN(_gen__24_),
    .Q(cmd)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _gen__45_ (
    .A(next_state),
    .B(3'h6),
    .Y(_gen__01_)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _gen__46_ (
    .A(next_state),
    .B(3'h4),
    .Y(_gen__02_)
  );
  \$logic_not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _gen__47_ (
    .A(next_state),
    .Y(_gen__08_)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd8),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd8),
    .Y_WIDTH(32'd1)
  ) _gen__48_ (
    .A(cmd),
    .B(8'h96),
    .Y(_gen__11_)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _gen__49_ (
    .A(cmd[2:0]),
    .B(3'h2),
    .Y(_gen__12_)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _gen__50_ (
    .A(cmd[2:0]),
    .B(3'h5),
    .Y(_gen__13_)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _gen__51_ (
    .A(cmd[2:0]),
    .B(3'h6),
    .Y(_gen__14_)
  );
  \$ge  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd5),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd5),
    .Y_WIDTH(32'd1)
  ) _gen__52_ (
    .A(counter),
    .B(cmd[7:3]),
    .Y(_gen__15_)
  );
  \$gt  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd5),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd32),
    .Y_WIDTH(32'd1)
  ) _gen__53_ (
    .A(window_counter),
    .B(32'd30),
    .Y(_gen__16_)
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__54_ (
    .A(_gen__16_),
    .B(_gen__07_),
    .Y(_gen__04_)
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__55_ (
    .A(_gen__22_),
    .B(_gen__09_),
    .Y(_gen__17_)
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__56_ (
    .A(cmd_filled),
    .B(_gen__11_),
    .Y(_gen__18_)
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__57_ (
    .A(cmd_filled),
    .B(_gen__12_),
    .Y(_gen__19_)
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__58_ (
    .A(cmd_filled),
    .B(_gen__13_),
    .Y(_gen__20_)
  );
  \$logic_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__59_ (
    .A(cmd_filled),
    .B(_gen__14_),
    .Y(_gen__21_)
  );
  \$logic_not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__60_ (
    .A(cmd_filled),
    .Y(_gen__22_)
  );
  \$logic_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__61_ (
    .A(_gen__17_),
    .B(_gen__10_),
    .Y(_gen__23_)
  );
  \$logic_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__62_ (
    .A(_gen__23_),
    .B(_gen__07_),
    .Y(_gen__24_)
  );
  \$logic_or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__63_ (
    .A(state[1]),
    .B(state[0]),
    .Y(_gen__25_)
  );
  \$ne  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _gen__64_ (
    .A(state),
    .B(next_state),
    .Y(_gen__26_)
  );
  \$ne  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _gen__65_ (
    .A(cmd[2:0]),
    .B(3'h2),
    .Y(_gen__27_)
  );
  \$or  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__66_ (
    .A(_gen__08_),
    .B(window_elapsed),
    .Y(tapp_active)
  );
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(5'h00),
    .CLK_POLARITY(1'h1),
    .WIDTH(32'd5)
  ) _gen__67_ (
    .ARST(prim_rstb),
    .CLK(prim_gclk),
    .D(_gen__03_),
    .Q(window_counter)
  );
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(1'h1),
    .WIDTH(32'd1)
  ) window_elapsed_reg /* _gen__68_ */ (
    .ARST(prim_rstb),
    .CLK(prim_gclk),
    .D(_gen__04_),
    .Q(window_elapsed)
  );
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(1'h0),
    .WIDTH(32'd1)
  ) tscan_exe_reg /* _gen__69_ */ (
    .ARST(trstb),
    .CLK(tck),
    .D(_gen__02_),
    .Q(tscan_exe)
  );
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(1'h0),
    .CLK_POLARITY(1'h0),
    .WIDTH(32'd1)
  ) tscan_enable_reg /* _gen__70_ */ (
    .ARST(trstb),
    .CLK(tck),
    .D(_gen__01_),
    .Q(tscan_enable)
  );
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(5'h00),
    .CLK_POLARITY(1'h0),
    .WIDTH(32'd5)
  ) _gen__71_ (
    .ARST(trstb),
    .CLK(tck),
    .D(_gen__00_),
    .Q(counter)
  );
  \$adff  #(
    .ARST_POLARITY(32'd0),
    .ARST_VALUE(3'h1),
    .CLK_POLARITY(1'h0),
    .WIDTH(32'd3)
  ) _gen__72_ (
    .ARST(trstb),
    .CLK(tck),
    .D(next_state),
    .Q(state)
  );
  \$mux  #(
    .WIDTH(32'd5)
  ) _gen__73_ (
    .A(5'h00),
    .B(_gen__06_),
    .S(_gen__25_),
    .Y(_gen__28_)
  );
  \$mux  #(
    .WIDTH(32'd5)
  ) _gen__74_ (
    .A(_gen__28_),
    .B(5'h00),
    .S(_gen__26_),
    .Y(_gen__00_)
  );
  \$pmux  #(
    .S_WIDTH(32'd5),
    .WIDTH(32'd3)
  ) _gen__75_ (
    .A(3'h0),
    .B({ 3'h3, _gen__33_, _gen__34_, _gen__37_, _gen__38_ }),
    .S({ _gen__07_, _gen__10_, _gen__09_, _gen__30_, _gen__29_ }),
    .Y(next_state)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _gen__76_ (
    .A(state),
    .B(3'h4),
    .Y(_gen__29_)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _gen__77_ (
    .A(state),
    .B(3'h6),
    .Y(_gen__30_)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _gen__78_ (
    .A(state),
    .B(3'h7),
    .Y(_gen__09_)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _gen__79_ (
    .A(state),
    .B(3'h3),
    .Y(_gen__10_)
  );
  \$eq  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _gen__80_ (
    .A(state),
    .B(3'h1),
    .Y(_gen__07_)
  );
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd5),
    .Y_WIDTH(32'd1)
  ) _gen__81_ (
    .A(window_counter),
    .Y(_gen__31_)
  );
  \$reduce_and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd3),
    .Y_WIDTH(32'd1)
  ) _gen__82_ (
    .A(counter[2:0]),
    .Y(cmd_filled)
  );
  \$mux  #(
    .WIDTH(32'd32)
  ) _gen__83_ (
    .A(32'd1),
    .B(32'd0),
    .S(_gen__31_),
    .Y(_gen__32_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _gen__84_ (
    .A(3'h3),
    .B(3'h7),
    .S(_gen__18_),
    .Y(_gen__33_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _gen__85_ (
    .A(_gen__35_),
    .B(3'h6),
    .S(_gen__19_),
    .Y(_gen__34_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _gen__86_ (
    .A(_gen__36_),
    .B(3'h6),
    .S(_gen__20_),
    .Y(_gen__35_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _gen__87_ (
    .A(3'h7),
    .B(3'h6),
    .S(_gen__21_),
    .Y(_gen__36_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _gen__88_ (
    .A(3'h6),
    .B(3'h4),
    .S(scan_filled),
    .Y(_gen__37_)
  );
  \$mux  #(
    .WIDTH(32'd3)
  ) _gen__89_ (
    .A(3'h4),
    .B(3'h6),
    .S(texe_done),
    .Y(_gen__38_)
  );
  assign _gen__05_[4:0] = _gen__03_;
  assign tde = tscan_enable;
endmodule

module top(ms_osc, ms_hporb, ms_trstb, ms_tck, ms_tdi, ms_tdo, ms_tde, ms_adc_eoc, ms_adc_data, ms_adc_soc, ms_adc_clk, ms_afe_sel, ms_afe_phase, ms_afe_phase_update, ms_urx, ms_utx);
  input ms_osc;
  wire ms_osc;
  input ms_hporb;
  wire ms_hporb;
  input ms_trstb;
  wire ms_trstb;
  input ms_tck;
  wire ms_tck;
  input ms_tdi;
  wire ms_tdi;
  output ms_tdo;
  wire ms_tdo;
  output ms_tde;
  wire ms_tde;
  input ms_adc_eoc;
  wire ms_adc_eoc;
  input [11:0] ms_adc_data;
  wire [11:0] ms_adc_data;
  output ms_adc_soc;
  wire ms_adc_soc;
  output ms_adc_clk;
  wire ms_adc_clk;
  output [3:0] ms_afe_sel;
  wire [3:0] ms_afe_sel;
  output [3:0] ms_afe_phase;
  wire [3:0] ms_afe_phase;
  output ms_afe_phase_update;
  wire ms_afe_phase_update;
  input ms_urx;
  wire ms_urx;
  output ms_utx;
  wire ms_utx;
  wire meas_eoc_p;
  wire meas_eop;
  wire [2:0] meas_state;
  wire prim_app_active;
  wire prim_clk;
  wire prim_dis;
  wire [6:0] prim_div;
  wire prim_gclk;
  wire prim_rstb;
  wire tapp_active;
  wire texe_done;
  wire tprim_burst_done;
  wire tscan_enable;
  wire tscan_end;
  wire tscan_exe;
  wire tscan_start;
  wire tuart_burst_done;
  wire uart_app_active;
  wire uart_clk;
  wire uart_dis;
  wire [6:0] uart_div;
  wire uart_gclk;
  wire uart_rstb;
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _gen__0_ (
    .A(tprim_burst_done),
    .B(tuart_burst_done),
    .Y(texe_done)
  );
  ana_ctrl ana_ctrl (
    .atpg(1'h0),
    .meas_eoc_p(meas_eoc_p),
    .meas_eop(meas_eop),
    .meas_state(meas_state),
    .ms_adc_clk(ms_adc_clk),
    .ms_adc_eoc(ms_adc_eoc),
    .ms_adc_soc(ms_adc_soc),
    .ms_afe_phase(ms_afe_phase),
    .ms_afe_phase_update(ms_afe_phase_update),
    .ms_afe_sel(ms_afe_sel),
    .prim_clk(prim_clk),
    .prim_rstb(prim_rstb),
    .trig(1'h1)
  );
  opcg prim_burst (
    .clk(prim_clk),
    .gclk(prim_gclk),
    .gclk_app_active(prim_app_active),
    .gclk_rstb(prim_rstb),
    .tapp_active(tapp_active),
    .tck(ms_tck),
    .texe_done(tprim_burst_done),
    .trstb(ms_trstb),
    .tscan_exe(tscan_exe)
  );
  \$paramod$b564b14d9fd308e618b07377286ecb02226d23aa\clock_divider  prim_clk_div (
    .clk(ms_osc),
    .dis(1'h0),
    .div(7'h00),
    .gclk(prim_gclk),
    .grstb(prim_rstb),
    .rstb(ms_hporb)
  );
  tap tap (
    .prim_gclk(prim_gclk),
    .prim_rstb(prim_rstb),
    .tapp_active(tapp_active),
    .tck(ms_tck),
    .tde(ms_tde),
    .tdi(ms_tdi),
    .tdo(ms_tdo),
    .texe_done(texe_done),
    .trstb(ms_trstb),
    .tscan_enable(tscan_enable),
    .tscan_end(tscan_end),
    .tscan_exe(tscan_exe),
    .tscan_start(tscan_start)
  );
  opcg uart_burst (
    .clk(uart_clk),
    .gclk(uart_gclk),
    .gclk_app_active(uart_app_active),
    .gclk_rstb(uart_rstb),
    .tapp_active(tapp_active),
    .tck(ms_tck),
    .texe_done(tuart_burst_done),
    .trstb(ms_trstb),
    .tscan_exe(tscan_exe)
  );
  \$paramod$b564b14d9fd308e618b07377286ecb02226d23aa\clock_divider  uart_clk_div (
    .clk(ms_osc),
    .dis(1'h0),
    .div(7'h03),
    .gclk(uart_gclk),
    .grstb(uart_rstb),
    .rstb(ms_hporb)
  );
  assign prim_dis = 1'h0;
  assign prim_div = 7'h00;
  assign uart_dis = 1'h0;
  assign uart_div = 7'h03;
endmodule
